
//load user profile
GET http://localhost:3000/users?id=60d20ceef39ef70ad45b1401
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImxhZ2dlciIsInVzZXJJZCI6IjYwZDIwY2VlZjM5ZWY3MGFkNDViMTQwMSIsImlhdCI6MTYyNDM3ODYxNn0.mmWIvCsazmyodabashsR-D2oTgBc6gcLLYW0YW-WIf8

###
//update profile
PUT http://localhost:3000/users?id=60d20ceef39ef70ad45b1401
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImxhZ2dlciIsInVzZXJJZCI6IjYwZDIwY2VlZjM5ZWY3MGFkNDViMTQwMSIsImlhdCI6MTYyNDM3ODYxNn0.mmWIvCsazmyodabashsR-D2oTgBc6gcLLYW0YW-WIf8
Content-Type: application/json

{
    "updateClaim": {
        "address": "HCM",
        "phoneNumber": "0123456789",
        "email": "minhduc@gmail.com",
        "company": "HAHA",
        "name": "cai gi day"
    }
}
###

//Login
POST http://localhost:3000/users/login 
Content-Type: application/json

{
    "username": "lagger",
    "password": "123456"
}

###
//register
POST http://localhost:3000/users/register
Content-Type: application/json

{
    "username": "lagger",
    "password": "123456",
    "claims": {
        "address": "QNa",
        "phoneNumber": "0984318328",
        "email": "test@gmail.com",
        "company": "DGroup",
        "name": "Truong Huu MInh Duc"
    }
}


