
//load user profile
GET http://localhost:3000/users?id=60d048f5a3b429358c4147d0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImxhZ2dlciIsInVzZXJJZCI6IjYwZDA0OGY1YTNiNDI5MzU4YzQxNDdkMCIsImlhdCI6MTYyNDI2ODE0OH0.jhmyO36sMjlB_U0PxS0QgmLu8nz7p2lMVHzra3CjuPw

###
//update profile
PUT http://localhost:3000/users?id=60d048f5a3b429358c4147d0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImxhZ2dlciIsInVzZXJJZCI6IjYwZDA0OGY1YTNiNDI5MzU4YzQxNDdkMCIsImlhdCI6MTYyNDI2ODE0OH0.jhmyO36sMjlB_U0PxS0QgmLu8nz7p2lMVHzra3CjuPw
Content-Type: application/json

{
    "updateClaim": {
        "address": "QNA",
        "phoneNumber": "0123456789",
        "email": "minhduc@gmail.com",
        "company": "DCoop"
    }
}
###

//Login
POST http://localhost:3000/users/login 
Content-Type: application/json

{
    "username": "lagger",
    "password": "123456"
}

###
//register
POST http://localhost:3000/users/register
Content-Type: application/json

{
    "username": "lagger",
    "password": "123456",
    "claims": {
        "address": "QNa",
        "phoneNumber": "0984318328",
        "email": "test@gmail.com",
        "company": "DGroup"
    }
}


